# Minimal Jekyll config for GitHub Pages
theme: minima  # GitHub Pages' default theme
markdown: kramdown

# Set the base URL for GitHub Pages (optional, replace with your repository name if necessary)
# baseurl: "/your-repo-name"

# Site settings (optional, but useful)
title: Food Computing Group
description: Welcome to our Food Computing Group
baseurl: ""
url: "http://fkg-india.github.io" # Replace with your website URL
author: Your Name

markdown: kramdown

# Exclude these files and folders from the site (optional)
exclude:
  - Gemfile
  - Gemfile.lock

# Enable pagination (optional, needed if you're using blog posts or pagination)
plugins:
  - jekyll-paginate

# Ensure GitHub Pages compatible gems are used
plugins:  
  - jekyll-feed  
  - jekyll-paginate  
  - github-pages



# Any other configurations or plugins you want to add (optional)
