# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# Site settings
title: Food Computing Lab
subtitle: "FoodComputing@Ashoka - from Bytes to Bites, everything in between"
description: "The official group website for the Multimedia Food Computing group at Ashoka University, where we explore interdisciplinary research on AI x Food x Data."
email: foodcomputing.ashoka@gmail.com
url: "https://fkg-india.github.io/"
logo : "/assets/images/logo/ashoka_uni_light.png"
mmfood_logo : "/assets/images/logo/mmfood_logo.png"


#theme
remote_theme: mmistakes/minimal-mistakes
light_theme               : "contrast"
dark_theme                : "dark"
minimal_mistakes_skin: contrast # "air", "aqua", "sunrise", "dark", "dirt", "neon", "mint", "plum", "default"
search: false

# Site Settings
locale: "en-US"

author:
  name   : ""
  avatar : "/assets/images/logo/mmfood_logo.png"
  location : "Ashoka University, India"
  bio    : "<b>Guiding Philosophy:</b><br> Food for Thought, Thought for Food"
  links:
    - label: "foodcomputing.ashoka@gmail.com"
      icon: "fas fa-envelope"
      url: "mailto:foodcomputing.ashoka@gmail.com"

# Build settings
markdown: kramdown
timezone:	Asia/Calcutta

include:
  - _pages

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

footer:

# Disable feed links
atom_feed:
  hide: true

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      author_profile: true
      classes: wide
      toc: true
      toc_sticky: true
      toc_label: "Jump To"
      toc_icon: "cogs"